#!/usr/bin/env bash
echo "Restoring dotfiles..."
RESTORE_PATH=$(dirname $(realpath $0))
find $RESTORE_PATH -mindepth 1 -maxdepth 1 -type d -printf '%f\n' |grep -v ^.git|xargs stow -v -t ~
vim -c VundleUpdate -c quitall
